version: '3'

services:
  nginx:
    ports:
      - 17680:80
    networks:
      app_net: 
        ipv4_address: 172.16.2.2

  php:
    networks:
      app_net: 
        ipv4_address: 172.16.2.4

  mariadb:
    ports:
      - 17606:3306
    networks:
      app_net: 
        ipv4_address: 172.16.2.8

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.2.0/28

